version: "2"
linters:
  default: all
  disable:
    - depguard
    - goimports
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    misspell:
      locale: US
    nakedret:
      max-func-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/lawzava/emailscraper
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
