name: scrape
version: '1.3.2'
summary: CLI utility to scrape emails from websites
description: |
  CLI utility that scrapes emails from specified website recursively and concurrently

  Sample call: `scrape -website https://lawzava.com -depth 2`

  **Parameters**
              --async             Scrape website pages asynchronously (default true)
          -d, --depth int         Max depth to follow when scraping recursively (default 3)
              --emails            Scrape emails (default true)
              --follow-external   Follow external 3rd party links within website
          -h, --help              help for scrape
              --js                Enables JS execution await (not supported throuh snap yet)
              --logs              Print debug logs
              --recursively       Scrape website recursively (default true)
          -w, --website string    Website to scrape (default "https://lawzava.com")
confinement: strict
base: core18
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: nil
    build-snaps: [go]
    source: .
    source-type: git
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build -o ../../../prime/bin/scrape
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
