name: scrape
version: '1.10.0'
summary: CLI utility to scrape emails from websites
description: |
  CLI utility that scrapes emails from specified website recursively and concurrently

  Sample call: `scrape -w lawzava.com`
confinement: strict
base: core24
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: go
    source: .
    build-snaps:
      - go/latest/stable
    build-environment:
      - CGO_ENABLED: "0"
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
