name: scrape
version: '1.7.0'
summary: CLI utility to scrape emails from websites
description: |
  CLI utility that scrapes emails from specified website recursively and concurrently

  Sample call: `scrape -w lawzava.com`
confinement: strict
base: core20
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: nil
    build-snaps: [go]
    source: .
    source-type: git
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build -o ../../../prime/bin/scrape
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
