# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrape < Formula
  desc "CLI utility to scrape emails from websites"
  homepage "https://github.com/lawzava/scrape"
  version "1.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lawzava/scrape/releases/download/v1.10.1/scrape_darwin_amd64.tar.gz"
      sha256 "87c4119d35be8c11f7a1d786cbf36342fec060934587e05b0362d704c9af2c7c"

      define_method(:install) do
        bin.install "scrape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lawzava/scrape/releases/download/v1.10.1/scrape_darwin_arm64.tar.gz"
      sha256 "aef80c66f2bb1322c5b8228878c4cd9cffecadd0b31ec3b26517396059fa1c9c"

      define_method(:install) do
        bin.install "scrape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lawzava/scrape/releases/download/v1.10.1/scrape_linux_amd64.tar.gz"
      sha256 "58f73dc0563de65d5ffbcb649f28a516c2eab5a7012b2f40816fddc3c6b50d19"
      define_method(:install) do
        bin.install "scrape"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lawzava/scrape/releases/download/v1.10.1/scrape_linux_armv6.tar.gz"
      sha256 "b0ad5fc23fdfe8926be822d7f8e3241b93c043fbec89b0e695cfb1d08305bc21"
      define_method(:install) do
        bin.install "scrape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lawzava/scrape/releases/download/v1.10.1/scrape_linux_arm64.tar.gz"
      sha256 "3c475e7b01410b8fca5600a3b925fb5177f66637fa2ea0eafcaaded36ead56ca"
      define_method(:install) do
        bin.install "scrape"
      end
    end
  end
end
